[package]
name = "statusbar"
version = "0.1.1"
edition = "2024"

[dependencies]
time = { version = "0", features = ["formatting", "local-offset"] }
zbus = "5"
tokio = { version = "1", features = ["full"] }